version: '3'

networks:
  default:
    driver: bridge

services:
  db:
    networks:
      - default
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: gdemost
    volumes:
      - "./data:/var/lib/mysql"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1235:1235"
    networks:
      - default
    depends_on:
      - db
    environment:
      MYSQL_HOST: "db:3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "gdemost"


