version: '3'

networks:
  default:
    driver: bridge

services:
  db:
    networks:
      - default
#    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: gdemost
    volumes:
      - "./data:/var/lib/mysql"
  app:
    image: registry.handh.ru/gdemost/back:latest
    restart: always
    ports:
      - "1235:1235"
    networks:
      - default
    depends_on:
      - db
    environment:
      MYSQL_HOST: "db:3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "gdemost"


